-- ==================== AUTO JJs BR - MODO HUMANO AVANÇADO ====================
local Players = game:GetService("Players")
local TextChatService = game:GetService("TextChatService")
local player = Players.LocalPlayer

-- Lista base completa até 1000
local baseWords = {
    [1] = "UM", [2] = "DOIS", [3] = "TRÊS", [4] = "QUATRO", [5] = "CINCO",
    [6] = "SEIS", [7] = "SETE", [8] = "OITO", [9] = "NOVE", [10] = "DEZ",
    [11] = "ONZE", [12] = "DOZE", [13] = "TREZE", [14] = "QUATORZE", [15] = "QUINZE",
    [16] = "DEZESSEIS", [17] = "DEZESSETE", [18] = "DEZOITO", [19] = "DEZENOVE", [20] = "VINTE",
    [21] = "VINTE E UM", [22] = "VINTE E DOIS", [23] = "VINTE E TRÊS", [24] = "VINTE E QUATRO", [25] = "VINTE E CINCO",
    [26] = "VINTE E SEIS", [27] = "VINTE E SETE", [28] = "VINTE E OITO", [29] = "VINTE E NOVE", [30] = "TRINTA",
    [31] = "TRINTA E UM", [32] = "TRINTA E DOIS", [33] = "TRINTA E TRÊS", [34] = "TRINTA E QUATRO", [35] = "TRINTA E CINCO",
    [36] = "TRINTA E SEIS", [37] = "TRINTA E SETE", [38] = "TRINTA E OITO", [39] = "TRINTA E NOVE", [40] = "QUARENTA",
    [41] = "QUARENTA E UM", [42] = "QUARENTA E DOIS", [43] = "QUARENTA E TRÊS", [44] = "QUARENTA E QUATRO", [45] = "QUARENTA E CINCO",
    [46] = "QUARENTA E SEIS", [47] = "QUARENTA E SETE", [48] = "QUARENTA E OITO", [49] = "QUARENTA E NOVE", [50] = "CINQUENTA",
    [51] = "CINQUENTA E UM", [52] = "CINQUENTA E DOIS", [53] = "CINQUENTA E TRÊS", [54] = "CINQUENTA E QUATRO", [55] = "CINQUENTA E CINCO",
    [56] = "CINQUENTA E SEIS", [57] = "CINQUENTA E SETE", [58] = "CINQUENTA E OITO", [59] = "CINQUENTA E NOVE", [60] = "SESSENTA",
    [61] = "SESSENTA E UM", [62] = "SESSENTA E DOIS", [63] = "SESSENTA E TRÊS", [64] = "SESSENTA E QUATRO", [65] = "SESSENTA E CINCO",
    [66] = "SESSENTA E SEIS", [67] = "SESSENTA E SETE", [68] = "SESSENTA E OITO", [69] = "SESSENTA E NOVE", [70] = "SETENTA",
    [71] = "SETENTA E UM", [72] = "SETENTA E DOIS", [73] = "SETENTA E TRÊS", [74] = "SETENTA E QUATRO", [75] = "SETENTA E CINCO",
    [76] = "SETENTA E SEIS", [77] = "SETENTA E SETE", [78] = "SETENTA E OITO", [79] = "SETENTA E NOVE", [80] = "OITENTA",
    [81] = "OITENTA E UM", [82] = "OITENTA E DOIS", [83] = "OITENTA E TRÊS", [84] = "OITENTA E QUATRO", [85] = "OITENTA E CINCO",
    [86] = "OITENTA E SEIS", [87] = "OITENTA E SETE", [88] = "OITENTA E OITO", [89] = "OITENTA E NOVE", [90] = "NOVENTA",
    [91] = "NOVENTA E UM", [92] = "NOVENTA E DOIS", [93] = "NOVENTA E TRÊS", [94] = "NOVENTA E QUATRO", [95] = "NOVENTA E CINCO",
    [96] = "NOVENTA E SEIS", [97] = "NOVENTA E SETE", [98] = "NOVENTA E OITO", [99] = "NOVENTA E NOVE", [100] = "CEM",
    [101] = "CENTO E UM", [102] = "CENTO E DOIS", [103] = "CENTO E TRÊS", [104] = "CENTO E QUATRO", [105] = "CENTO E CINCO",
    [106] = "CENTO E SEIS", [107] = "CENTO E SETE", [108] = "CENTO E OITO", [109] = "CENTO E NOVE", [110] = "CENTO E DEZ",
    [111] = "CENTO E ONZE", [112] = "CENTO E DOZE", [113] = "CENTO E TREZE", [114] = "CENTO E QUATORZE", [115] = "CENTO E QUINZE",
    [116] = "CENTO E DEZESSEIS", [117] = "CENTO E DEZESSETE", [118] = "CENTO E DEZOITO", [119] = "CENTO E DEZENOVE", [120] = "CENTO E VINTE",
    [121] = "CENTO E VINTE E UM", [122] = "CENTO E VINTE E DOIS", [123] = "CENTO E VINTE E TRÊS", [124] = "CENTO E VINTE E QUATRO", [125] = "CENTO E VINTE E CINCO",
    [126] = "CENTO E VINTE E SEIS", [127] = "CENTO E VINTE E SETE", [128] = "CENTO E VINTE E OITO", [129] = "CENTO E VINTE E NOVE", [130] = "CENTO E TRINTA",
    [131] = "CENTO E TRINTA E UM", [132] = "CENTO E TRINTA E DOIS", [133] = "CENTO E TRINTA E TRÊS", [134] = "CENTO E TRINTA E QUATRO", [135] = "CENTO E TRINTA E CINCO",
    [136] = "CENTO E TRINTA E SEIS", [137] = "CENTO E TRINTA E SETE", [138] = "CENTO E TRINTA E OITO", [139] = "CENTO E TRINTA E NOVE", [140] = "CENTO E QUARENTA",
    [141] = "CENTO E QUARENTA E UM", [142] = "CENTO E QUARENTA E DOIS", [143] = "CENTO E QUARENTA E TRÊS", [144] = "CENTO E QUARENTA E QUATRO", [145] = "CENTO E QUARENTA E CINCO",
    [146] = "CENTO E QUARENTA E SEIS", [147] = "CENTO E QUARENTA E SETE", [148] = "CENTO E QUARENTA E OITO", [149] = "CENTO E QUARENTA E NOVE", [150] = "CENTO E CINQUENTA",
    [151] = "CENTO E CINQUENTA E UM", [152] = "CENTO E CINQUENTA E DOIS", [153] = "CENTO E CINQUENTA E TRÊS", [154] = "CENTO E CINQUENTA E QUATRO", [155] = "CENTO E CINQUENTA E CINCO",
    [156] = "CENTO E CINQUENTA E SEIS", [157] = "CENTO E CINQUENTA E SETE", [158] = "CENTO E CINQUENTA E OITO", [159] = "CENTO E CINQUENTA E NOVE", [160] = "CENTO E SESSENTA",
    [161] = "CENTO E SESSENTA E UM", [162] = "CENTO E SESSENTA E DOIS", [163] = "CENTO E SESSENTA E TRÊS", [164] = "CENTO E SESSENTA E QUATRO", [165] = "CENTO E SESSENTA E CINCO",
    [166] = "CENTO E SESSENTA E SEIS", [167] = "CENTO E SESSENTA E SETE", [168] = "CENTO E SESSENTA E OITO", [169] = "CENTO E SESSENTA E NOVE", [170] = "CENTO E SETENTA",
    [171] = "CENTO E SETENTA E UM", [172] = "CENTO E SETENTA E DOIS", [173] = "CENTO E SETENTA E TRÊS", [174] = "CENTO E SETENTA E QUATRO", [175] = "CENTO E SETENTA E CINCO",
    [176] = "CENTO E SETENTA E SEIS", [177] = "CENTO E SETENTA E SETE", [178] = "CENTO E SETENTA E OITO", [179] = "CENTO E SETENTA E NOVE", [180] = "CENTO E OITENTA",
    [181] = "CENTO E OITENTA E UM", [182] = "CENTO E OITENTA E DOIS", [183] = "CENTO E OITENTA E TRÊS", [184] = "CENTO E OITENTA E QUATRO", [185] = "CENTO E OITENTA E CINCO",
    [186] = "CENTO E OITENTA E SEIS", [187] = "CENTO E OITENTA E SETE", [188] = "CENTO E OITENTA E OITO", [189] = "CENTO E OITENTA E NOVE", [190] = "CENTO E NOVENTA",
    [191] = "CENTO E NOVENTA E UM", [192] = "CENTO E NOVENTA E DOIS", [193] = "CENTO E NOVENTA E TRÊS", [194] = "CENTO E NOVENTA E QUATRO", [195] = "CENTO E NOVENTA E CINCO",
    [196] = "CENTO E NOVENTA E SEIS", [197] = "CENTO E NOVENTA E SETE", [198] = "CENTO E NOVENTA E OITO", [199] = "CENTO E NOVENTA E NOVE", [200] = "DUZENTOS",
    [201] = "DUZENTOS E UM", [202] = "DUZENTOS E DOIS", [203] = "DUZENTOS E TRÊS", [204] = "DUZENTOS E QUATRO", [205] = "DUZENTOS E CINCO",
    [206] = "DUZENTOS E SEIS", [207] = "DUZENTOS E SETE", [208] = "DUZENTOS E OITO", [209] = "DUZENTOS E NOVE", [210] = "DUZENTOS E DEZ",
    [211] = "DUZENTOS E ONZE", [212] = "DUZENTOS E DOZE", [213] = "DUZENTOS E TREZE", [214] = "DUZENTOS E QUATORZE", [215] = "DUZENTOS E QUINZE",
    [216] = "DUZENTOS E DEZESSEIS", [217] = "DUZENTOS E DEZESSETE", [218] = "DUZENTOS E DEZOITO", [219] = "DUZENTOS E DEZENOVE", [220] = "DUZENTOS E VINTE",
    [221] = "DUZENTOS E VINTE E UM", [222] = "DUZENTOS E VINTE E DOIS", [223] = "DUZENTOS E VINTE E TRÊS", [224] = "DUZENTOS E VINTE E QUATRO", [225] = "DUZENTOS E VINTE E CINCO",
    [226] = "DUZENTOS E VINTE E SEIS", [227] = "DUZENTOS E VINTE E SETE", [228] = "DUZENTOS E VINTE E OITO", [229] = "DUZENTOS E VINTE E NOVE", [230] = "DUZENTOS E TRINTA",
    [231] = "DUZENTOS E TRINTA E UM", [232] = "DUZENTOS E TRINTA E DOIS", [233] = "DUZENTOS E TRINTA E TRÊS", [234] = "DUZENTOS E TRINTA E QUATRO", [235] = "DUZENTOS E TRINTA E CINCO",
    [236] = "DUZENTOS E TRINTA E SEIS", [237] = "DUZENTOS E TRINTA E SETE", [238] = "DUZENTOS E TRINTA E OITO", [239] = "DUZENTOS E TRINTA E NOVE", [240] = "DUZENTOS E QUARENTA",
    [241] = "DUZENTOS E QUARENTA E UM", [242] = "DUZENTOS E QUARENTA E DOIS", [243] = "DUZENTOS E QUARENTA E TRÊS", [244] = "DUZENTOS E QUARENTA E QUATRO", [245] = "DUZENTOS E QUARENTA E CINCO",
    [246] = "DUZENTOS E QUARENTA E SEIS", [247] = "DUZENTOS E QUARENTA E SETE", [248] = "DUZENTOS E QUARENTA E OITO", [249] = "DUZENTOS E QUARENTA E NOVE", [250] = "DUZENTOS E CINQUENTA",
    [251] = "DUZENTOS E CINQUENTA E UM", [252] = "DUZENTOS E CINQUENTA E DOIS", [253] = "DUZENTOS E CINQUENTA E TRÊS", [254] = "DUZENTOS E CINQUENTA E QUATRO", [255] = "DUZENTOS E CINQUENTA E CINCO",
    [256] = "DUZENTOS E CINQUENTA E SEIS", [257] = "DUZENTOS E CINQUENTA E SETE", [258] = "DUZENTOS E CINQUENTA E OITO", [259] = "DUZENTOS E CINQUENTA E NOVE", [260] = "DUZENTOS E SESSENTA",
    [261] = "DUZENTOS E SESSENTA E UM", [262] = "DUZENTOS E SESSENTA E DOIS", [263] = "DUZENTOS E SESSENTA E TRÊS", [264] = "DUZENTOS E SESSENTA E QUATRO", [265] = "DUZENTOS E SESSENTA E CINCO",
    [266] = "DUZENTOS E SESSENTA E SEIS", [267] = "DUZENTOS E SESSENTA E SETE", [268] = "DUZENTOS E SESSENTA E OITO", [269] = "DUZENTOS E SESSENTA E NOVE", [270] = "DUZENTOS E SETENTA",
    [271] = "DUZENTOS E SETENTA E UM", [272] = "DUZENTOS E SETENTA E DOIS", [273] = "DUZENTOS E SETENTA E TRÊS", [274] = "DUZENTOS E SETENTA E QUATRO", [275] = "DUZENTOS E SETENTA E CINCO",
    [276] = "DUZENTOS E SETENTA E SEIS", [277] = "DUZENTOS E SETENTA E SETE", [278] = "DUZENTOS E SETENTA E OITO", [279] = "DUZENTOS E SETENTA E NOVE", [280] = "DUZENTOS E OITENTA",
    [281] = "DUZENTOS E OITENTA E UM", [282] = "DUZENTOS E OITENTA E DOIS", [283] = "DUZENTOS E OITENTA E TRÊS", [284] = "DUZENTOS E OITENTA E QUATRO", [285] = "DUZENTOS E OITENTA E CINCO",
    [286] = "DUZENTOS E OITENTA E SEIS", [287] = "DUZENTOS E OITENTA E SETE", [288] = "DUZENTOS E OITENTA E OITO", [289] = "DUZENTOS E OITENTA E NOVE", [290] = "DUZENTOS E NOVENTA",
    [291] = "DUZENTOS E NOVENTA E UM", [292] = "DUZENTOS E NOVENTA E DOIS", [293] = "DUZENTOS E NOVENTA E TRÊS", [294] = "DUZENTOS E NOVENTA E QUATRO", [295] = "DUZENTOS E NOVENTA E CINCO",
    [296] = "DUZENTOS E NOVENTA E SEIS", [297] = "DUZENTOS E NOVENTA E SETE", [298] = "DUZENTOS E NOVENTA E OITO", [299] = "DUZENTOS E NOVENTA E NOVE", [300] = "TREZENTOS",
    [301] = "TREZENTOS E UM", [302] = "TREZENTOS E DOIS", [303] = "TREZENTOS E TRÊS", [304] = "TREZENTOS E QUATRO", [305] = "TREZENTOS E CINCO",
    [306] = "TREZENTOS E SEIS", [307] = "TREZENTOS E SETE", [308] = "TREZENTOS E OITO", [309] = "TREZENTOS E NOVE", [310] = "TREZENTOS E DEZ",
    [311] = "TREZENTOS E ONZE", [312] = "TREZENTOS E DOZE", [313] = "TREZENTOS E TREZE", [314] = "TREZENTOS E QUATORZE", [315] = "TREZENTOS E QUINZE",
    [316] = "TREZENTOS E DEZESSEIS", [317] = "TREZENTOS E DEZESSETE", [318] = "TREZENTOS E DEZOITO", [319] = "TREZENTOS E DEZENOVE", [320] = "TREZENTOS E VINTE",
    [321] = "TREZENTOS E VINTE E UM", [322] = "TREZENTOS E VINTE E DOIS", [323] = "TREZENTOS E VINTE E TRÊS", [324] = "TREZENTOS E VINTE E QUATRO", [325] = "TREZENTOS E VINTE E CINCO",
    [326] = "TREZENTOS E VINTE E SEIS", [327] = "TREZENTOS E VINTE E SETE", [328] = "TREZENTOS E VINTE E OITO", [329] = "TREZENTOS E VINTE E NOVE", [330] = "TREZENTOS E TRINTA",
    [331] = "TREZENTOS E TRINTA E UM", [332] = "TREZENTOS E TRINTA E DOIS", [333] = "TREZENTOS E TRINTA E TRÊS", [334] = "TREZENTOS E TRINTA E QUATRO", [335] = "TREZENTOS E TRINTA E CINCO",
    [336] = "TREZENTOS E TRINTA E SEIS", [337] = "TREZENTOS E TRINTA E SETE", [338] = "TREZENTOS E TRINTA E OITO", [339] = "TREZENTOS E TRINTA E NOVE", [340] = "TREZENTOS E QUARENTA",
    [341] = "TREZENTOS E QUARENTA E UM", [342] = "TREZENTOS E QUARENTA E DOIS", [343] = "TREZENTOS E QUARENTA E TRÊS", [344] = "TREZENTOS E QUARENTA E QUATRO", [345] = "TREZENTOS E QUARENTA E CINCO",
    [346] = "TREZENTOS E QUARENTA E SEIS", [347] = "TREZENTOS E QUARENTA E SETE", [348] = "TREZENTOS E QUARENTA E OITO", [349] = "TREZENTOS E QUARENTA E NOVE", [350] = "TREZENTOS E CINQUENTA",
    [351] = "TREZENTOS E CINQUENTA E UM", [352] = "TREZENTOS E CINQUENTA E DOIS", [353] = "TREZENTOS E CINQUENTA E TRÊS", [354] = "TREZENTOS E CINQUENTA E QUATRO", [355] = "TREZENTOS E CINQUENTA E CINCO",
    [356] = "TREZENTOS E CINQUENTA E SEIS", [357] = "TREZENTOS E CINQUENTA E SETE", [358] = "TREZENTOS E CINQUENTA E OITO", [359] = "TREZENTOS E CINQUENTA E NOVE", [360] = "TREZENTOS E SESSENTA",
    [361] = "TREZENTOS E SESSENTA E UM", [362] = "TREZENTOS E SESSENTA E DOIS", [363] = "TREZENTOS E SESSENTA E TRÊS", [364] = "TREZENTOS E SESSENTA E QUATRO", [365] = "TREZENTOS E SESSENTA E CINCO",
    [366] = "TREZENTOS E SESSENTA E SEIS", [367] = "TREZENTOS E SESSENTA E SETE", [368] = "TREZENTOS E SESSENTA E OITO", [369] = "TREZENTOS E SESSENTA E NOVE", [370] = "TREZENTOS E SETENTA",
    [371] = "TREZENTOS E SETENTA E UM", [372] = "TREZENTOS E SETENTA E DOIS", [373] = "TREZENTOS E SETENTA E TRÊS", [374] = "TREZENTOS E SETENTA E QUATRO", [375] = "TREZENTOS E SETENTA E CINCO",
    [376] = "TREZENTOS E SETENTA E SEIS", [377] = "TREZENTOS E SETENTA E SETE", [378] = "TREZENTOS E SETENTA E OITO", [379] = "TREZENTOS E SETENTA E NOVE", [380] = "TREZENTOS E OITENTA",
    [381] = "TREZENTOS E OITENTA E UM", [382] = "TREZENTOS E OITENTA E DOIS", [383] = "TREZENTOS E OITENTA E TRÊS", [384] = "TREZENTOS E OITENTA E QUATRO", [385] = "TREZENTOS E OITENTA E CINCO",
    [386] = "TREZENTOS E OITENTA E SEIS", [387] = "TREZENTOS E OITENTA E SETE", [388] = "TREZENTOS E OITENTA E OITO", [389] = "TREZENTOS E OITENTA E NOVE", [390] = "TREZENTOS E NOVENTA",
    [391] = "TREZENTOS E NOVENTA E UM", [392] = "TREZENTOS E NOVENTA E DOIS", [393] = "TREZENTOS E NOVENTA E TRÊS", [394] = "TREZENTOS E NOVENTA E QUATRO", [395] = "TREZENTOS E NOVENTA E CINCO",
    [396] = "TREZENTOS E NOVENTA E SEIS", [397] = "TREZENTOS E NOVENTA E SETE", [398] = "TREZENTOS E NOVENTA E OITO", [399] = "TREZENTOS E NOVENTA E NOVE", [400] = "QUATROCENTOS",
    [401] = "QUATROCENTOS E UM", [402] = "QUATROCENTOS E DOIS", [403] = "QUATROCENTOS E TRÊS", [404] = "QUATROCENTOS E QUATRO", [405] = "QUATROCENTOS E CINCO",
    [406] = "QUATROCENTOS E SEIS", [407] = "QUATROCENTOS E SETE", [408] = "QUATROCENTOS E OITO", [409] = "QUATROCENTOS E NOVE", [410] = "QUATROCENTOS E DEZ",
    [411] = "QUATROCENTOS E ONZE", [412] = "QUATROCENTOS E DOZE", [413] = "QUATROCENTOS E TREZE", [414] = "QUATROCENTOS E QUATORZE", [415] = "QUATROCENTOS E QUINZE",
    [416] = "QUATROCENTOS E DEZESSEIS", [417] = "QUATROCENTOS E DEZESSETE", [418] = "QUATROCENTOS E DEZOITO", [419] = "QUATROCENTOS E DEZENOVE", [420] = "QUATROCENTOS E VINTE",
    [421] = "QUATROCENTOS E VINTE E UM", [422] = "QUATROCENTOS E VINTE E DOIS", [423] = "QUATROCENTOS E VINTE E TRÊS", [424] = "QUATROCENTOS E VINTE E QUATRO", [425] = "QUATROCENTOS E VINTE E CINCO",
    [426] = "QUATROCENTOS E VINTE E SEIS", [427] = "QUATROCENTOS E VINTE E SETE", [428] = "QUATROCENTOS E VINTE E OITO", [429] = "QUATROCENTOS E VINTE E NOVE", [430] = "QUATROCENTOS E TRINTA",
    [431] = "QUATROCENTOS E TRINTA E UM", [432] = "QUATROCENTOS E TRINTA E DOIS", [433] = "QUATROCENTOS E TRINTA E TRÊS", [434] = "QUATROCENTOS E TRINTA E QUATRO", [435] = "QUATROCENTOS E TRINTA E CINCO",
    [436] = "QUATROCENTOS E TRINTA E SEIS", [437] = "QUATROCENTOS E TRINTA E SETE", [438] = "QUATROCENTOS E TRINTA E OITO", [439] = "QUATROCENTOS E TRINTA E NOVE", [440] = "QUATROCENTOS E QUARENTA",
    [441] = "QUATROCENTOS E QUARENTA E UM", [442] = "QUATROCENTOS E QUARENTA E DOIS", [443] = "QUATROCENTOS E QUARENTA E TRÊS", [444] = "QUATROCENTOS E QUARENTA E QUATRO", [445] = "QUATROCENTOS E QUARENTA E CINCO",
    [446] = "QUATROCENTOS E QUARENTA E SEIS", [447] = "QUATROCENTOS E QUARENTA E SETE", [448] = "QUATROCENTOS E QUARENTA E OITO", [449] = "QUATROCENTOS E QUARENTA E NOVE", [450] = "QUATROCENTOS E CINQUENTA",
    [451] = "QUATROCENTOS E CINQUENTA E UM", [452] = "QUATROCENTOS E CINQUENTA E DOIS", [453] = "QUATROCENTOS E CINQUENTA E TRÊS", [454] = "QUATROCENTOS E CINQUENTA E QUATRO", [455] = "QUATROCENTOS E CINQUENTA E CINCO",
    [456] = "QUATROCENTOS E CINQUENTA E SEIS", [457] = "QUATROCENTOS E CINQUENTA E SETE", [458] = "QUATROCENTOS E CINQUENTA E OITO", [459] = "QUATROCENTOS E CINQUENTA E NOVE", [460] = "QUATROCENTOS E SESSENTA",
    [461] = "QUATROCENTOS E SESSENTA E UM", [462] = "QUATROCENTOS E SESSENTA E DOIS", [463] = "QUATROCENTOS E SESSENTA E TRÊS", [464] = "QUATROCENTOS E SESSENTA E QUATRO", [465] = "QUATROCENTOS E SESSENTA E CINCO",
    [466] = "QUATROCENTOS E SESSENTA E SEIS", [467] = "QUATROCENTOS E SESSENTA E SETE", [468] = "QUATROCENTOS E SESSENTA E OITO", [469] = "QUATROCENTOS E SESSENTA E NOVE", [470] = "QUATROCENTOS E SETENTA",
    [471] = "QUATROCENTOS E SETENTA E UM", [472] = "QUATROCENTOS E SETENTA E DOIS", [473] = "QUATROCENTOS E SETENTA E TRÊS", [474] = "QUATROCENTOS E SETENTA E QUATRO", [475] = "QUATROCENTOS E SETENTA E CINCO",
    [476] = "QUATROCENTOS E SETENTA E SEIS", [477] = "QUATROCENTOS E SETENTA E SETE", [478] = "QUATROCENTOS E SETENTA E OITO", [479] = "QUATROCENTOS E SETENTA E NOVE", [480] = "QUATROCENTOS E OITENTA",
    [481] = "QUATROCENTOS E OITENTA E UM", [482] = "QUATROCENTOS E OITENTA E DOIS", [483] = "QUATROCENTOS E OITENTA E TRÊS", [484] = "QUATROCENTOS E OITENTA E QUATRO", [485] = "QUATROCENTOS E OITENTA E CINCO",
    [486] = "QUATROCENTOS E OITENTA E SEIS", [487] = "QUATROCENTOS E OITENTA E SETE", [488] = "QUATROCENTOS E OITENTA E OITO", [489] = "QUATROCENTOS E OITENTA E NOVE", [490] = "QUATROCENTOS E NOVENTA",
    [491] = "QUATROCENTOS E NOVENTA E UM", [492] = "QUATROCENTOS E NOVENTA E DOIS", [493] = "QUATROCENTOS E NOVENTA E TRÊS", [494] = "QUATROCENTOS E NOVENTA E QUATRO", [495] = "QUATROCENTOS E NOVENTA E CINCO",
    [496] = "QUATROCENTOS E NOVENTA E SEIS", [497] = "QUATROCENTOS E NOVENTA E SETE", [498] = "QUATROCENTOS E NOVENTA E OITO", [499] = "QUATROCENTOS E NOVENTA E NOVE", [500] = "QUINHENTOS",
    [501] = "QUINHENTOS E UM", [502] = "QUINHENTOS E DOIS", [503] = "QUINHENTOS E TRÊS", [504] = "QUINHENTOS E QUATRO", [505] = "QUINHENTOS E CINCO",
    [506] = "QUINHENTOS E SEIS", [507] = "QUINHENTOS E SETE", [508] = "QUINHENTOS E OITO", [509] = "QUINHENTOS E NOVE", [510] = "QUINHENTOS E DEZ",
    [511] = "QUINHENTOS E ONZE", [512] = "QUINHENTOS E DOZE", [513] = "QUINHENTOS E TREZE", [514] = "QUINHENTOS E QUATORZE", [515] = "QUINHENTOS E QUINZE",
    [516] = "QUINHENTOS E DEZESSEIS", [517] = "QUINHENTOS E DEZESSETE", [518] = "QUINHENTOS E DEZOITO", [519] = "QUINHENTOS E DEZENOVE", [520] = "QUINHENTOS E VINTE",
    [521] = "QUINHENTOS E VINTE E UM", [522] = "QUINHENTOS E VINTE E DOIS", [523] = "QUINHENTOS E VINTE E TRÊS", [524] = "QUINHENTOS E VINTE E QUATRO", [525] = "QUINHENTOS E VINTE E CINCO",
    [526] = "QUINHENTOS E VINTE E SEIS", [527] = "QUINHENTOS E VINTE E SETE", [528] = "QUINHENTOS E VINTE E OITO", [529] = "QUINHENTOS E VINTE E NOVE", [530] = "QUINHENTOS E TRINTA",
    [531] = "QUINHENTOS E TRINTA E UM", [532] = "QUINHENTOS E TRINTA E DOIS", [533] = "QUINHENTOS E TRINTA E TRÊS", [534] = "QUINHENTOS E TRINTA E QUATRO", [535] = "QUINHENTOS E TRINTA E CINCO",
    [536] = "QUINHENTOS E TRINTA E SEIS", [537] = "QUINHENTOS E TRINTA E SETE", [538] = "QUINHENTOS E TRINTA E OITO", [539] = "QUINHENTOS E TRINTA E NOVE", [540] = "QUINHENTOS E QUARENTA",
    [541] = "QUINHENTOS E QUARENTA E UM", [542] = "QUINHENTOS E QUARENTA E DOIS", [543] = "QUINHENTOS E QUARENTA E TRÊS", [544] = "QUINHENTOS E QUARENTA E QUATRO", [545] = "QUINHENTOS E QUARENTA E CINCO",
    [546] = "QUINHENTOS E QUARENTA E SEIS", [547] = "QUINHENTOS E QUARENTA E SETE", [548] = "QUINHENTOS E QUARENTA E OITO", [549] = "QUINHENTOS E QUARENTA E NOVE", [550] = "QUINHENTOS E CINQUENTA",
    [551] = "QUINHENTOS E CINQUENTA E UM", [552] = "QUINHENTOS E CINQUENTA E DOIS", [553] = "QUINHENTOS E CINQUENTA E TRÊS", [554] = "QUINHENTOS E CINQUENTA E QUATRO", [555] = "QUINHENTOS E CINQUENTA E CINCO",
    [556] = "QUINHENTOS E CINQUENTA E SEIS", [557] = "QUINHENTOS E CINQUENTA E SETE", [558] = "QUINHENTOS E CINQUENTA E OITO", [559] = "QUINHENTOS E CINQUENTA E NOVE", [560] = "QUINHENTOS E SESSENTA",
    [561] = "QUINHENTOS E SESSENTA E UM", [562] = "QUINHENTOS E SESSENTA E DOIS", [563] = "QUINHENTOS E SESSENTA E TRÊS", [564] = "QUINHENTOS E SESSENTA E QUATRO", [565] = "QUINHENTOS E SESSENTA E CINCO",
    [566] = "QUINHENTOS E SESSENTA E SEIS", [567] = "QUINHENTOS E SESSENTA E SETE", [568] = "QUINHENTOS E SESSENTA E OITO", [569] = "QUINHENTOS E SESSENTA E NOVE", [570] = "QUINHENTOS E SETENTA",
    [571] = "QUINHENTOS E SETENTA E UM", [572] = "QUINHENTOS E SETENTA E DOIS", [573] = "QUINHENTOS E SETENTA E TRÊS", [574] = "QUINHENTOS E SETENTA E QUATRO", [575] = "QUINHENTOS E SETENTA E CINCO",
    [576] = "QUINHENTOS E SETENTA E SEIS", [577] = "QUINHENTOS E SETENTA E SETE", [578] = "QUINHENTOS E SETENTA E OITO", [579] = "QUINHENTOS E SETENTA E NOVE", [580] = "QUINHENTOS E OITENTA",
    [581] = "QUINHENTOS E OITENTA E UM", [582] = "QUINHENTOS E OITENTA E DOIS", [583] = "QUINHENTOS E OITENTA E TRÊS", [584] = "QUINHENTOS E OITENTA E QUATRO", [585] = "QUINHENTOS E OITENTA E CINCO",
    [586] = "QUINHENTOS E OITENTA E SEIS", [587] = "QUINHENTOS E OITENTA E SETE", [588] = "QUINHENTOS E OITENTA E OITO", [589] = "QUINHENTOS E OITENTA E NOVE", [590] = "QUINHENTOS E NOVENTA",
    [591] = "QUINHENTOS E NOVENTA E UM", [592] = "QUINHENTOS E NOVENTA E DOIS", [593] = "QUINHENTOS E NOVENTA E TRÊS", [594] = "QUINHENTOS E NOVENTA E QUATRO", [595] = "QUINHENTOS E NOVENTA E CINCO",
    [596] = "QUINHENTOS E NOVENTA E SEIS", [597] = "QUINHENTOS E NOVENTA E SETE", [598] = "QUINHENTOS E NOVENTA E OITO", [599] = "QUINHENTOS E NOVENTA E NOVE", [600] = "SEISCENTOS",
    [601] = "SEISCENTOS E UM", [602] = "SEISCENTOS E DOIS", [603] = "SEISCENTOS E TRÊS", [604] = "SEISCENTOS E QUATRO", [605] = "SEISCENTOS E CINCO",
    [606] = "SEISCENTOS E SEIS", [607] = "SEISCENTOS E SETE", [608] = "SEISCENTOS E OITO", [609] = "SEISCENTOS E NOVE", [610] = "SEISCENTOS E DEZ",
    [611] = "SEISCENTOS E ONZE", [612] = "SEISCENTOS E DOZE", [613] = "SEISCENTOS E TREZE", [614] = "SEISCENTOS E QUATORZE", [615] = "SEISCENTOS E QUINZE",
    [616] = "SEISCENTOS E DEZESSEIS", [617] = "SEISCENTOS E DEZESSETE", [618] = "SEISCENTOS E DEZOITO", [619] = "SEISCENTOS E DEZENOVE", [620] = "SEISCENTOS E VINTE",
    [621] = "SEISCENTOS E VINTE E UM", [622] = "SEISCENTOS E VINTE E DOIS", [623] = "SEISCENTOS E VINTE E TRÊS", [624] = "SEISCENTOS E VINTE E QUATRO", [625] = "SEISCENTOS E VINTE E CINCO",
    [626] = "SEISCENTOS E VINTE E SEIS", [627] = "SEISCENTOS E VINTE E SETE", [628] = "SEISCENTOS E VINTE E OITO", [629] = "SEISCENTOS E VINTE E NOVE", [630] = "SEISCENTOS E TRINTA",
    [631] = "SEISCENTOS E TRINTA E UM", [632] = "SEISCENTOS E TRINTA E DOIS", [633] = "SEISCENTOS E TRINTA E TRÊS", [634] = "SEISCENTOS E TRINTA E QUATRO", [635] = "SEISCENTOS E TRINTA E CINCO",
    [636] = "SEISCENTOS E TRINTA E SEIS", [637] = "SEISCENTOS E TRINTA E SETE", [638] = "SEISCENTOS E TRINTA E OITO", [639] = "SEISCENTOS E TRINTA E NOVE", [640] = "SEISCENTOS E QUARENTA",
    [641] = "SEISCENTOS E QUARENTA E UM", [642] = "SEISCENTOS E QUARENTA E DOIS", [643] = "SEISCENTOS E QUARENTA E TRÊS", [644] = "SEISCENTOS E QUARENTA E QUATRO", [645] = "SEISCENTOS E QUARENTA E CINCO",
    [646] = "SEISCENTOS E QUARENTA E SEIS", [647] = "SEISCENTOS E QUARENTA E SETE", [648] = "SEISCENTOS E QUARENTA E OITO", [649] = "SEISCENTOS E QUARENTA E NOVE", [650] = "SEISCENTOS E CINQUENTA",
    [651] = "SEISCENTOS E CINQUENTA E UM", [652] = "SEISCENTOS E CINQUENTA E DOIS", [653] = "SEISCENTOS E CINQUENTA E TRÊS", [654] = "SEISCENTOS E CINQUENTA E QUATRO", [655] = "SEISCENTOS E CINQUENTA E CINCO",
    [656] = "SEISCENTOS E CINQUENTA E SEIS", [657] = "SEISCENTOS E CINQUENTA E SETE", [658] = "SEISCENTOS E CINQUENTA E OITO", [659] = "SEISCENTOS E CINQUENTA E NOVE", [660] = "SEISCENTOS E SESSENTA",
    [661] = "SEISCENTOS E SESSENTA E UM", [662] = "SEISCENTOS E SESSENTA E DOIS", [663] = "SEISCENTOS E SESSENTA E TRÊS", [664] = "SEISCENTOS E SESSENTA E QUATRO", [665] = "SEISCENTOS E SESSENTA E CINCO",
    [666] = "SEISCENTOS E SESSENTA E SEIS", [667] = "SEISCENTOS E SESSENTA E SETE", [668] = "SEISCENTOS E SESSENTA E OITO", [669] = "SEISCENTOS E SESSENTA E NOVE", [670] = "SEISCENTOS E SETENTA",
    [671] = "SEISCENTOS E SETENTA E UM", [672] = "SEISCENTOS E SETENTA E DOIS", [673] = "SEISCENTOS E SETENTA E TRÊS", [674] = "SEISCENTOS E SETENTA E QUATRO", [675] = "SEISCENTOS E SETENTA E CINCO",
    [676] = "SEISCENTOS E SETENTA E SEIS", [677] = "SEISCENTOS E SETENTA E SETE", [678] = "SEISCENTOS E SETENTA E OITO", [679] = "SEISCENTOS E SETENTA E NOVE", [680] = "SEISCENTOS E OITENTA",
    [681] = "SEISCENTOS E OITENTA E UM", [682] = "SEISCENTOS E OITENTA E DOIS", [683] = "SEISCENTOS E OITENTA E TRÊS", [684] = "SEISCENTOS E OITENTA E QUATRO", [685] = "SEISCENTOS E OITENTA E CINCO",
    [686] = "SEISCENTOS E OITENTA E SEIS", [687] = "SEISCENTOS E OITENTA E SETE", [688] = "SEISCENTOS E OITENTA E OITO", [689] = "SEISCENTOS E OITENTA E NOVE", [690] = "SEISCENTOS E NOVENTA",
    [691] = "SEISCENTOS E NOVENTA E UM", [692] = "SEISCENTOS E NOVENTA E DOIS", [693] = "SEISCENTOS E NOVENTA E TRÊS", [694] = "SEISCENTOS E NOVENTA E QUATRO", [695] = "SEISCENTOS E NOVENTA E CINCO",
    [696] = "SEISCENTOS E NOVENTA E SEIS", [697] = "SEISCENTOS E NOVENTA E SETE", [698] = "SEISCENTOS E NOVENTA E OITO", [699] = "SEISCENTOS E NOVENTA E NOVE", [700] = "SETECENTOS",
    [701] = "SETECENTOS E UM", [702] = "SETECENTOS E DOIS", [703] = "SETECENTOS E TRÊS", [704] = "SETECENTOS E QUATRO", [705] = "SETECENTOS E CINCO",
    [706] = "SETECENTOS E SEIS", [707] = "SETECENTOS E SETE", [708] = "SETECENTOS E OITO", [709] = "SETECENTOS E NOVE", [710] = "SETECENTOS E DEZ",
    [711] = "SETECENTOS E ONZE", [712] = "SETECENTOS E DOZE", [713] = "SETECENTOS E TREZE", [714] = "SETECENTOS E QUATORZE", [715] = "SETECENTOS E QUINZE",
    [716] = "SETECENTOS E DEZESSEIS", [717] = "SETECENTOS E DEZESSETE", [718] = "SETECENTOS E DEZOITO", [719] = "SETECENTOS E DEZENOVE", [720] = "SETECENTOS E VINTE",
    [721] = "SETECENTOS E VINTE E UM", [722] = "SETECENTOS E VINTE E DOIS", [723] = "SETECENTOS E VINTE E TRÊS", [724] = "SETECENTOS E VINTE E QUATRO", [725] = "SETECENTOS E VINTE E CINCO",
    [726] = "SETECENTOS E VINTE E SEIS", [727] = "SETECENTOS E VINTE E SETE", [728] = "SETECENTOS E VINTE E OITO", [729] = "SETECENTOS E VINTE E NOVE", [730] = "SETECENTOS E TRINTA",
    [731] = "SETECENTOS E TRINTA E UM", [732] = "SETECENTOS E TRINTA E DOIS", [733] = "SETECENTOS E TRINTA E TRÊS", [734] = "SETECENTOS E TRINTA E QUATRO", [735] = "SETECENTOS E TRINTA E CINCO",
    [736] = "SETECENTOS E TRINTA E SEIS", [737] = "SETECENTOS E TRINTA E SETE", [738] = "SETECENTOS E TRINTA E OITO", [739] = "SETECENTOS E TRINTA E NOVE", [740] = "SETECENTOS E QUARENTA",
    [741] = "SETECENTOS E QUARENTA E UM", [742] = "SETECENTOS E QUARENTA E DOIS", [743] = "SETECENTOS E QUARENTA E TRÊS", [744] = "SETECENTOS E QUARENTA E QUATRO", [745] = "SETECENTOS E QUARENTA E CINCO",
    [746] = "SETECENTOS E QUARENTA E SEIS", [747] = "SETECENTOS E QUARENTA E SETE", [748] = "SETECENTOS E QUARENTA E OITO", [749] = "SETECENTOS E QUARENTA E NOVE", [750] = "SETECENTOS E CINQUENTA",
    [751] = "SETECENTOS E CINQUENTA E UM", [752] = "SETECENTOS E CINQUENTA E DOIS", [753] = "SETECENTOS E CINQUENTA E TRÊS", [754] = "SETECENTOS E CINQUENTA E QUATRO", [755] = "SETECENTOS E CINQUENTA E CINCO",
    [756] = "SETECENTOS E CINQUENTA E SEIS", [757] = "SETECENTOS E CINQUENTA E SETE", [758] = "SETECENTOS E CINQUENTA E OITO", [759] = "SETECENTOS E CINQUENTA E NOVE", [760] = "SETECENTOS E SESSENTA",
    [761] = "SETECENTOS E SESSENTA E UM", [762] = "SETECENTOS E SESSENTA E DOIS", [763] = "SETECENTOS E SESSENTA E TRÊS", [764] = "SETECENTOS E SESSENTA E QUATRO", [765] = "SETECENTOS E SESSENTA E CINCO",
    [766] = "SETECENTOS E SESSENTA E SEIS", [767] = "SETECENTOS E SESSENTA E SETE", [768] = "SETECENTOS E SESSENTA E OITO", [769] = "SETECENTOS E SESSENTA E NOVE", [770] = "SETECENTOS E SETENTA",
    [771] = "SETECENTOS E SETENTA E UM", [772] = "SETECENTOS E SETENTA E DOIS", [773] = "SETECENTOS E SETENTA E TRÊS", [774] = "SETECENTOS E SETENTA E QUATRO", [775] = "SETECENTOS E SETENTA E CINCO",
    [776] = "SETECENTOS E SETENTA E SEIS", [777] = "SETECENTOS E SETENTA E SETE", [778] = "SETECENTOS E SETENTA E OITO", [779] = "SETECENTOS E SETENTA E NOVE", [780] = "SETECENTOS E OITENTA",
    [781] = "SETECENTOS E OITENTA E UM", [782] = "SETECENTOS E OITENTA E DOIS", [783] = "SETECENTOS E OITENTA E TRÊS", [784] = "SETECENTOS E OITENTA E QUATRO", [785] = "SETECENTOS E OITENTA E CINCO",
    [786] = "SETECENTOS E OITENTA E SEIS", [787] = "SETECENTOS E OITENTA E SETE", [788] = "SETECENTOS E OITENTA E OITO", [789] = "SETECENTOS E OITENTA E NOVE", [790] = "SETECENTOS E NOVENTA",
    [791] = "SETECENTOS E NOVENTA E UM", [792] = "SETECENTOS E NOVENTA E DOIS", [793] = "SETECENTOS E NOVENTA E TRÊS", [794] = "SETECENTOS E NOVENTA E QUATRO", [795] = "SETECENTOS E NOVENTA E CINCO",
    [796] = "SETECENTOS E NOVENTA E SEIS", [797] = "SETECENTOS E NOVENTA E SETE", [798] = "SETECENTOS E NOVENTA E OITO", [799] = "SETECENTOS E NOVENTA E NOVE", [800] = "OITOCENTOS",
    [801] = "OITOCENTOS E UM", [802] = "OITOCENTOS E DOIS", [803] = "OITOCENTOS E TRÊS", [804] = "OITOCENTOS E QUATRO", [805] = "OITOCENTOS E CINCO",
    [806] = "OITOCENTOS E SEIS", [807] = "OITOCENTOS E SETE", [808] = "OITOCENTOS E OITO", [809] = "OITOCENTOS E NOVE", [810] = "OITOCENTOS E DEZ",
    [811] = "OITOCENTOS E ONZE", [812] = "OITOCENTOS E DOZE", [813] = "OITOCENTOS E TREZE", [814] = "OITOCENTOS E QUATORZE", [815] = "OITOCENTOS E QUINZE",
    [816] = "OITOCENTOS E DEZESSEIS", [817] = "OITOCENTOS E DEZESSETE", [818] = "OITOCENTOS E DEZOITO", [819] = "OITOCENTOS E DEZENOVE", [820] = "OITOCENTOS E VINTE",
    [821] = "OITOCENTOS E VINTE E UM", [822] = "OITOCENTOS E VINTE E DOIS", [823] = "OITOCENTOS E VINTE E TRÊS", [824] = "OITOCENTOS E VINTE E QUATRO", [825] = "OITOCENTOS E VINTE E CINCO",
    [826] = "OITOCENTOS E VINTE E SEIS", [827] = "OITOCENTOS E VINTE E SETE", [828] = "OITOCENTOS E VINTE E OITO", [829] = "OITOCENTOS E VINTE E NOVE", [830] = "OITOCENTOS E TRINTA",
    [831] = "OITOCENTOS E TRINTA E UM", [832] = "OITOCENTOS E TRINTA E DOIS", [833] = "OITOCENTOS E TRINTA E TRÊS", [834] = "OITOCENTOS E TRINTA E QUATRO", [835] = "OITOCENTOS E TRINTA E CINCO",
    [836] = "OITOCENTOS E TRINTA E SEIS", [837] = "OITOCENTOS E TRINTA E SETE", [838] = "OITOCENTOS E TRINTA E OITO", [839] = "OITOCENTOS E TRINTA E NOVE", [840] = "OITOCENTOS E QUARENTA",
    [841] = "OITOCENTOS E QUARENTA E UM", [842] = "OITOCENTOS E QUARENTA E DOIS", [843] = "OITOCENTOS E QUARENTA E TRÊS", [844] = "OITOCENTOS E QUARENTA E QUATRO", [845] = "OITOCENTOS E QUARENTA E CINCO",
    [846] = "OITOCENTOS E QUARENTA E SEIS", [847] = "OITOCENTOS E QUARENTA E SETE", [848] = "OITOCENTOS E QUARENTA E OITO", [849] = "OITOCENTOS E QUARENTA E NOVE", [850] = "OITOCENTOS E CINQUENTA",
    [851] = "OITOCENTOS E CINQUENTA E UM", [852] = "OITOCENTOS E CINQUENTA E DOIS", [853] = "OITOCENTOS E CINQUENTA E TRÊS", [854] = "OITOCENTOS E CINQUENTA E QUATRO", [855] = "OITOCENTOS E CINQUENTA E CINCO",
    [856] = "OITOCENTOS E CINQUENTA E SEIS", [857] = "OITOCENTOS E CINQUENTA E SETE", [858] = "OITOCENTOS E CINQUENTA E OITO", [859] = "OITOCENTOS E CINQUENTA E NOVE", [860] = "OITOCENTOS E SESSENTA",
    [861] = "OITOCENTOS E SESSENTA E UM", [862] = "OITOCENTOS E SESSENTA E DOIS", [863] = "OITOCENTOS E SESSENTA E TRÊS", [864] = "OITOCENTOS E SESSENTA E QUATRO", [865] = "OITOCENTOS E SESSENTA E CINCO",
    [866] = "OITOCENTOS E SESSENTA E SEIS", [867] = "OITOCENTOS E SESSENTA E SETE", [868] = "OITOCENTOS E SESSENTA E OITO", [869] = "OITOCENTOS E SESSENTA E NOVE", [870] = "OITOCENTOS E SETENTA",
    [871] = "OITOCENTOS E SETENTA E UM", [872] = "OITOCENTOS E SETENTA E DOIS", [873] = "OITOCENTOS E SETENTA E TRÊS", [874] = "OITOCENTOS E SETENTA E QUATRO", [875] = "OITOCENTOS E SETENTA E CINCO",
    [876] = "OITOCENTOS E SETENTA E SEIS", [877] = "OITOCENTOS E SETENTA E SETE", [878] = "OITOCENTOS E SETENTA E OITO", [879] = "OITOCENTOS E SETENTA E NOVE", [880] = "OITOCENTOS E OITENTA",
    [881] = "OITOCENTOS E OITENTA E UM", [882] = "OITOCENTOS E OITENTA E DOIS", [883] = "OITOCENTOS E OITENTA E TRÊS", [884] = "OITOCENTOS E OITENTA E QUATRO", [885] = "OITOCENTOS E OITENTA E CINCO",
    [886] = "OITOCENTOS E OITENTA E SEIS", [887] = "OITOCENTOS E OITENTA E SETE", [888] = "OITOCENTOS E OITENTA E OITO", [889] = "OITOCENTOS E OITENTA E NOVE", [890] = "OITOCENTOS E NOVENTA",
    [891] = "OITOCENTOS E NOVENTA E UM", [892] = "OITOCENTOS E NOVENTA E DOIS", [893] = "OITOCENTOS E NOVENTA E TRÊS", [894] = "OITOCENTOS E NOVENTA E QUATRO", [895] = "OITOCENTOS E NOVENTA E CINCO",
    [896] = "OITOCENTOS E NOVENTA E SEIS", [897] = "OITOCENTOS E NOVENTA E SETE", [898] = "OITOCENTOS E NOVENTA E OITO", [899] = "OITOCENTOS E NOVENTA E NOVE", [900] = "NOVECENTOS",
    [901] = "NOVECENTOS E UM", [902] = "NOVECENTOS E DOIS", [903] = "NOVECENTOS E TRÊS", [904] = "NOVECENTOS E QUATRO", [905] = "NOVECENTOS E CINCO",
    [906] = "NOVECENTOS E SEIS", [907] = "NOVECENTOS E SETE", [908] = "NOVECENTOS E OITO", [909] = "NOVECENTOS E NOVE", [910] = "NOVECENTOS E DEZ",
    [911] = "NOVECENTOS E ONZE", [912] = "NOVECENTOS E DOZE", [913] = "NOVECENTOS E TREZE", [914] = "NOVECENTOS E QUATORZE", [915] = "NOVECENTOS E QUINZE",
    [916] = "NOVECENTOS E DEZESSEIS", [917] = "NOVECENTOS E DEZESSETE", [918] = "NOVECENTOS E DEZOITO", [919] = "NOVECENTOS E DEZENOVE", [920] = "NOVECENTOS E VINTE",
    [921] = "NOVECENTOS E VINTE E UM", [922] = "NOVECENTOS E VINTE E DOIS", [923] = "NOVECENTOS E VINTE E TRÊS", [924] = "NOVECENTOS E VINTE E QUATRO", [925] = "NOVECENTOS E VINTE E CINCO",
    [926] = "NOVECENTOS E VINTE E SEIS", [927] = "NOVECENTOS E VINTE E SETE", [928] = "NOVECENTOS E VINTE E OITO", [929] = "NOVECENTOS E VINTE E NOVE", [930] = "NOVECENTOS E TRINTA",
    [931] = "NOVECENTOS E TRINTA E UM", [932] = "NOVECENTOS E TRINTA E DOIS", [933] = "NOVECENTOS E TRINTA E TRÊS", [934] = "NOVECENTOS E TRINTA E QUATRO", [935] = "NOVECENTOS E TRINTA E CINCO",
    [936] = "NOVECENTOS E TRINTA E SEIS", [937] = "NOVECENTOS E TRINTA E SETE", [938] = "NOVECENTOS E TRINTA E OITO", [939] = "NOVECENTOS E TRINTA E NOVE", [940] = "NOVECENTOS E QUARENTA",
    [941] = "NOVECENTOS E QUARENTA E UM", [942] = "NOVECENTOS E QUARENTA E DOIS", [943] = "NOVECENTOS E QUARENTA E TRÊS", [944] = "NOVECENTOS E QUARENTA E QUATRO", [945] = "NOVECENTOS E QUARENTA E CINCO",
    [946] = "NOVECENTOS E QUARENTA E SEIS", [947] = "NOVECENTOS E QUARENTA E SETE", [948] = "NOVECENTOS E QUARENTA E OITO", [949] = "NOVECENTOS E QUARENTA E NOVE", [950] = "NOVECENTOS E CINQUENTA",
    [951] = "NOVECENTOS E CINQUENTA E UM", [952] = "NOVECENTOS E CINQUENTA E DOIS", [953] = "NOVECENTOS E CINQUENTA E TRÊS", [954] = "NOVECENTOS E CINQUENTA E QUATRO", [955] = "NOVECENTOS E CINQUENTA E CINCO",
    [956] = "NOVECENTOS E CINQUENTA E SEIS", [957] = "NOVECENTOS E CINQUENTA E SETE", [958] = "NOVECENTOS E CINQUENTA E OITO", [959] = "NOVECENTOS E CINQUENTA E NOVE", [960] = "NOVECENTOS E SESSENTA",
    [961] = "NOVECENTOS E SESSENTA E UM", [962] = "NOVECENTOS E SESSENTA E DOIS", [963] = "NOVECENTOS E SESSENTA E TRÊS", [964] = "NOVECENTOS E SESSENTA E QUATRO", [965] = "NOVECENTOS E SESSENTA E CINCO",
    [966] = "NOVECENTOS E SESSENTA E SEIS", [967] = "NOVECENTOS E SESSENTA E SETE", [968] = "NOVECENTOS E SESSENTA E OITO", [969] = "NOVECENTOS E SESSENTA E NOVE", [970] = "NOVECENTOS E SETENTA",
    [971] = "NOVECENTOS E SETENTA E UM", [972] = "NOVECENTOS E SETENTA E DOIS", [973] = "NOVECENTOS E SETENTA E TRÊS", [974] = "NOVECENTOS E SETENTA E QUATRO", [975] = "NOVECENTOS E SETENTA E CINCO",
    [976] = "NOVECENTOS E SETENTA E SEIS", [977] = "NOVECENTOS E SETENTA E SETE", [978] = "NOVECENTOS E SETENTA E OITO", [979] = "NOVECENTOS E SETENTA E NOVE", [980] = "NOVECENTOS E OITENTA",
    [981] = "NOVECENTOS E OITENTA E UM", [982] = "NOVECENTOS E OITENTA E DOIS", [983] = "NOVECENTOS E OITENTA E TRÊS", [984] = "NOVECENTOS E OITENTA E QUATRO", [985] = "NOVECENTOS E OITENTA E CINCO",
    [986] = "NOVECENTOS E OITENTA E SEIS", [987] = "NOVECENTOS E OITENTA E SETE", [988] = "NOVECENTOS E OITENTA E OITO", [989] = "NOVECENTOS E OITENTA E NOVE", [990] = "NOVECENTOS E NOVENTA",
    [991] = "NOVECENTOS E NOVENTA E UM", [992] = "NOVECENTOS E NOVENTA E DOIS", [993] = "NOVECENTOS E NOVENTA E TRÊS", [994] = "NOVECENTOS E NOVENTA E QUATRO", [995] = "NOVECENTOS E NOVENTA E CINCO",
    [996] = "NOVECENTOS E NOVENTA E SEIS", [997] = "NOVECENTOS E NOVENTA E SETE", [998] = "NOVECENTOS E NOVENTA E OITO", [999] = "NOVECENTOS E NOVENTA E NOVE", [1000] = "MIL"
}

-- Variáveis - Modo Humano
local startNum = 1
local endNum = 20
local thinkDelayMin = 0.8
local thinkDelayMax = 2.2
local chatDelayMin = 3.8
local chatDelayMax = 5.5
local jumpDelay = 0.5
local suffix = "!"
local doJump = true
local running = false

-- Canal de chat
local generalChannel
if TextChatService.ChatVersion == Enum.ChatVersion.TextChatService then
    generalChannel = TextChatService:WaitForChild("TextChannels"):WaitForChild("RBXGeneral", 5)
end

-- ====================== GUI ======================
local screenGui = Instance.new("ScreenGui")
screenGui.Name = "AutoJJsBR_Humano"
screenGui.ResetOnSpawn = false
screenGui.Parent = (gethui and gethui()) or game:GetService("CoreGui") or player:WaitForChild("PlayerGui")

local mainFrame = Instance.new("Frame")
mainFrame.Size = UDim2.new(0, 380, 0, 680)
mainFrame.Position = UDim2.new(0.5, -190, 0.5, -340)
mainFrame.BackgroundColor3 = Color3.fromRGB(15, 35, 15)
mainFrame.BorderSizePixel = 0
mainFrame.Active = true
mainFrame.Draggable = true
mainFrame.Parent = screenGui
mainFrame.BackgroundTransparency = 0.1

local uiGradient = Instance.new("UIGradient")
uiGradient.Color = ColorSequence.new{ColorSequenceKeypoint.new(0, Color3.fromRGB(20, 60, 20)), ColorSequenceKeypoint.new(1, Color3.fromRGB(5, 25, 5))}
uiGradient.Rotation = 90
uiGradient.Parent = mainFrame

local uiCorner = Instance.new("UICorner")
uiCorner.CornerRadius = UDim.new(0, 16)
uiCorner.Parent = mainFrame

local uiStroke = Instance.new("UIStroke")
uiStroke.Color = Color3.fromRGB(0, 100, 0)
uiStroke.Thickness = 2
uiStroke.Transparency = 0.4
uiStroke.Parent = mainFrame

local title = Instance.new("TextLabel")
title.Size = UDim2.new(1, 0, 0, 50)
title.BackgroundTransparency = 1
title.Text = "AUTO JJs BR"
title.TextColor3 = Color3.fromRGB(200, 255, 200)
title.TextScaled = true
title.Font = Enum.Font.GothamBlack
title.TextSize = 28
title.Parent = mainFrame

local subtitle = Instance.new("TextLabel")
subtitle.Size = UDim2.new(1, 0, 0, 20)
subtitle.Position = UDim2.new(0, 0, 0, 45)
subtitle.BackgroundTransparency = 1
subtitle.Text = "Modo Humano Avançado (parece pessoa real)"
subtitle.TextColor3 = Color3.fromRGB(150, 255, 150)
subtitle.TextScaled = true
subtitle.Font = Enum.Font.Gotham
subtitle.TextSize = 14
subtitle.Parent = mainFrame

local closeBtn = Instance.new("TextButton")
closeBtn.Size = UDim2.new(0, 40, 0, 40)
closeBtn.Position = UDim2.new(1, -45, 0, 5)
closeBtn.BackgroundColor3 = Color3.fromRGB(180, 40, 40)
closeBtn.Text = "✕"
closeBtn.TextColor3 = Color3.new(1,1,1)
closeBtn.Font = Enum.Font.GothamBold
closeBtn.TextSize = 24
closeBtn.Parent = mainFrame
Instance.new("UICorner", closeBtn).CornerRadius = UDim.new(0, 10)
closeBtn.MouseButton1Click:Connect(function() screenGui:Destroy() end)

local function createLabel(text, posY)
    local lbl = Instance.new("TextLabel")
    lbl.Size = UDim2.new(0.9, 0, 0, 25)
    lbl.Position = UDim2.new(0.05, 0, 0, posY)
    lbl.BackgroundTransparency = 1
    lbl.Text = text
    lbl.TextColor3 = Color3.fromRGB(220, 255, 220)
    lbl.TextScaled = true
    lbl.Font = Enum.Font.GothamSemibold
    lbl.Parent = mainFrame
    return lbl
end

local function createBox(default, posY)
    local box = Instance.new("TextBox")
    box.Size = UDim2.new(0.9, 0, 0, 40)
    box.Position = UDim2.new(0.05, 0, 0, posY)
    box.BackgroundColor3 = Color3.fromRGB(10, 20, 10)
    box.Text = default
    box.TextColor3 = Color3.fromRGB(200, 255, 200)
    box.TextScaled = true
    box.Font = Enum.Font.Gotham
    box.ClearTextOnFocus = false
    Instance.new("UICorner", box).CornerRadius = UDim.new(0, 8)
    box.Parent = mainFrame
    return box
end

createLabel("Iniciar do número", 80)
local boxStart = createBox("1", 105)

createLabel("Até o número (máx 1000)", 150)
local boxEnd = createBox("20", 175)

createLabel("Tempo pensando/abrir chat (mín)", 220)
local boxThinkMin = createBox("0.8", 245)

createLabel("Tempo pensando/abrir chat (máx)", 290)
local boxThinkMax = createBox("2.2", 315)

createLabel("Delay entre mensagens (mín)", 360)
local boxChatMin = createBox("3.8", 385)

createLabel("Delay entre mensagens (máx)", 430)
local boxChatMax = createBox("5.5", 455)

createLabel("Delay do pulo após chat (s)", 500)
local boxJumpDelay = createBox("0.5", 525)

createLabel("Sufixo final (ex: !)", 570)
local boxSuffix = createBox("!", 595)

local toggleBtn = Instance.new("TextButton")
toggleBtn.Size = UDim2.new(0.9, 0, 0, 50)
toggleBtn.Position = UDim2.new(0.05, 0, 0, 640)
toggleBtn.BackgroundColor3 = Color3.fromRGB(0, 180, 0)
toggleBtn.Text = "PULAR: LIGADO ✓"
toggleBtn.TextColor3 = Color3.new(1,1,1)
toggleBtn.Font = Enum.Font.GothamBold
toggleBtn.TextSize = 20
toggleBtn.Parent = mainFrame
Instance.new("UICorner", toggleBtn).CornerRadius = UDim.new(0, 10)

toggleBtn.MouseButton1Click:Connect(function()
    doJump = not doJump
    toggleBtn.Text = doJump and "PULAR: LIGADO ✓" or "PULAR: DESLIGADO ✗"
    toggleBtn.BackgroundColor3 = doJump and Color3.fromRGB(0, 180, 0) or Color3.fromRGB(180, 0, 0)
end)

local status = Instance.new("TextLabel")
status.Size = UDim2.new(0.9, 0, 0, 40)
status.Position = UDim2.new(0.05, 0, 0, 700)
status.BackgroundTransparency = 1
status.Text = "Pronto para iniciar"
status.TextColor3 = Color3.fromRGB(255, 220, 100)
status.TextScaled = true
status.Font = Enum.Font.GothamSemibold
status.Parent = mainFrame

local startBtn = Instance.new("TextButton")
startBtn.Size = UDim2.new(0.43, 0, 0, 55)
startBtn.Position = UDim2.new(0.05, 0, 0, 750)
startBtn.BackgroundColor3 = Color3.fromRGB(0, 200, 0)
startBtn.Text = "INICIAR ▶"
startBtn.TextColor3 = Color3.new(1,1,1)
startBtn.Font = Enum.Font.GothamBlack
startBtn.TextSize = 22
startBtn.Parent = mainFrame
Instance.new("UICorner", startBtn).CornerRadius = UDim.new(0, 12)

local stopBtn = Instance.new("TextButton")
stopBtn.Size = UDim2.new(0.43, 0, 0, 55)
stopBtn.Position = UDim2.new(0.52, 0, 0, 750)
stopBtn.BackgroundColor3 = Color3.fromRGB(200, 0, 0)
stopBtn.Text = "PARAR ■"
stopBtn.TextColor3 = Color3.new(1,1,1)
stopBtn.Font = Enum.Font.GothamBlack
stopBtn.TextSize = 22
stopBtn.Parent = mainFrame
Instance.new("UICorner", stopBtn).CornerRadius = UDim.new(0, 12)

-- ====================== FUNÇÕES ======================
local function sendChat(msg)
    if generalChannel then
        generalChannel:SendAsync(msg)
    else
        warn("TextChannel não encontrado.")
        status.Text = "Erro: Chat não detectado"
        status.TextColor3 = Color3.fromRGB(255, 100, 100)
    end
end

local function startCounting()
    if running then return end
   
    startNum = tonumber(boxStart.Text) or 1
    endNum = tonumber(boxEnd.Text) or 20
    thinkDelayMin = tonumber(boxThinkMin.Text) or 0.8
    thinkDelayMax = tonumber(boxThinkMax.Text) or 2.2
    chatDelayMin = tonumber(boxChatMin.Text) or 3.8
    chatDelayMax = tonumber(boxChatMax.Text) or 5.5
    jumpDelay = tonumber(boxJumpDelay.Text) or 0.5
    suffix = boxSuffix.Text or "!"
   
    if startNum < 1 then startNum = 1 end
    if endNum > 1000 then endNum = 1000 end
    if startNum > endNum then
        status.Text = "Erro: Início maior que o fim!"
        status.TextColor3 = Color3.fromRGB(255, 100, 100)
        return
    end
   
    running = true
    status.Text = "Contando de forma humana... " .. startNum .. "/" .. endNum
    status.TextColor3 = Color3.fromRGB(100, 255, 100)
   
    for i = startNum, endNum do
        if not running then break end
       
        status.Text = "Contando... " .. i .. "/" .. endNum .. " (humano)"

        local textToSend = (baseWords[i] or tostring(i)) .. suffix

        -- Simula pessoa pensando / abrindo o chat
        local thinkTime = math.random() * (thinkDelayMax - thinkDelayMin) + thinkDelayMin
        task.wait(thinkTime)

        -- Envia a mensagem
        sendChat(textToSend)

        -- Pulo (se ligado)
        if doJump then
            task.spawn(function()
                task.wait(jumpDelay)
                local char = player.Character
                if char then
                    local humanoid = char:FindFirstChildOfClass("Humanoid")
                    if humanoid and humanoid:GetState() ~= Enum.HumanoidStateType.Jumping and humanoid.FloorMaterial ~= Enum.Material.Air then
                        humanoid:ChangeState(Enum.HumanoidStateType.Jumping)
                    end
                end
            end)
        end

        -- Delay entre as mensagens (parece humano)
        local randomDelay = math.random() * (chatDelayMax - chatDelayMin) + chatDelayMin
        task.wait(randomDelay)
    end
   
    running = false
    status.Text = "Finalizado! (" .. startNum .. " → " .. endNum .. ")"
    status.TextColor3 = Color3.fromRGB(255, 220, 100)
end

startBtn.MouseButton1Click:Connect(startCounting)
stopBtn.MouseButton1Click:Connect(function()
    running = false
    status.Text = "Parado manualmente"
    status.TextColor3 = Color3.fromRGB(255, 100, 100)
end)

print("✅ Auto JJs BR - Modo Humano Avançado carregado com sucesso!")
